server:
  port: 8080
  address: 0.0.0.0

  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

spring:
  mvc:
    static-path-pattern: /video/**
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://43.143.182.215:13306/douyin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B7
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

  redis:
    host: 43.143.182.215
    port: 6379
    database: 0
    password: redispwd

  servlet:
    multipart:
      max-file-size: -1     # 文件上传大小限制，设置最大值，不能超过该值，否则报错
#      max-file-size: 500KB      # 文件上传大小限制，设置最大值，不能超过该值，否则报错
      max-request-size: -1     # 文件最大请求限制，用于批量上传



# 整合mybatis
mybatis:
  type-aliases-package: com.rocky.pojo       # 所有pojo类所在的包路径
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true

# 通用mapper工具的配置
mapper:
  mappers: com.rocky.my.mapper.MyMapper      # 配置MyMapper，包含了一些封装好的CRUD方法
  not-empty: false                            # 在进行数据库操作的时候，username != null 是否会追加 username != ''
  identity: MYSQL

# 分页插件助手的配置
#pagehelper:
#  helper-dialect: MYSQL
#  support-methods-arguments: true

# 日志级别
logging:
  level:
    root: info
# MinIO 配置
minio:
  endpoint: http://43.143.182.215:9000      # MinIO服务地址
  fileHost: http://43.143.182.215:9000      # 文件地址host
  bucketName: douyin                      # 存储桶bucket名称
  accessKey: minioadmin                       # 用户名
  secretKey: minioadmin                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m


#  accessKey: root                         # 用户名
#  secretKey: douyin123                     # 密码
#  endpoint: http://8.134.113.47:9090
#  fileHost: http://8.134.113.47:9090